title: "[uzhguys]"
description: A young team of like-minded developers ready to change the world remotely
email: ihor@uzhguys.dev
show_downloads: false
google_analytics: G-BSTG7MXKR4
theme: jekyll-theme-hacker
